version: "3.8"

services:
  postgres:
    image: postgres:16
    container_name: tecarral_postgres
    environment:
      POSTGRES_DB: tecarral
      POSTGRES_USER: tecarral_user
      POSTGRES_PASSWORD: tecarral_pass
    ports:
      - "5432:5432"
    volumes:
      - tecarral_pgdata:/var/lib/postgresql/data

volumes:
  tecarral_pgdata:
